#--------------------------------------------------------IMAGE

apiVersion: v1
kind: Service
metadata:
  name: will-app
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: will-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-app
  namespace: dev
  labels:
    app: will-app
spec:
  selector:
    matchLabels:
      app: will-app
  template:
    metadata:
      labels:
        app: will-app
    spec:
      containers:
        - name: will-app
          image: wil42/playground:v1
          ports:
            - containerPort: 80
